config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show] do
    member do
      get :favorites
      get :myshops
      get :myreviews
    end
  end
  root to: "toppages#index"
  resources :shops, only: [:index, :show, :new, :create, :destroy]
  resources :reviews, only: [:show, :new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shop.rb
class Shop < ApplicationRecord
  validates :name, presence: true
  validates :kind, presence: true
  validates :address, presence: true
  validates :holiday, presence: true
  validates :image, presence: true
 
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_one_attached :image
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops = Shop.all.page(params[:page]).per(5)
  end
  
  def show
    @shop=Shop.find(params[:id])
    @reviews = @shop.reviews.page(params[:page]).per(3)
    session[:shop_id] = @shop.id
  end

  def new
    @shop = current_user.shops.build
  end

  def create
    @shop = current_user.shops.build(shop_params)
    if @shop.save
      flash[:success] = "店舗を作成しました"
      redirect_to @shop
    else
      flash.now[:danger] = "店舗作成に失敗しました"
      render :new 
    end
  end

  def destroy
    @shop = current_user.shops.find(params[:id])
    @shop.destroy
    flash[:success] = "店舗を削除しました"
    redirect_to shops_path
  end
  
  private
  
  def shop_params
    params.require(:shop).permit(:name, :kind, :address, :holiday, :image)
  end
end

app/views/shops/_shop_block.html.erb
<div class="container d-none d-md-block">
  <div class="row">
    <div class="col-4" style="height: 250px">
      <% if shop.image.attached? %>
          <%= image_tag shop.image, class: "rounded h-100 w-100"%>
      <% end %>
    </div>
    <div class="col-8">
      <div class="d-flex justify-content-between">
        <h2><%= shop.name%></h2>
        <div style="height: 1.5rem">
          <% if current_user == shop.user%>
              <%= link_to "削除する", shop, method: :delete, data: {confirm: "削除してよろしいですか？"}, class: "btn btn-danger btn-sm" %>
          <% end %>
        </div>
      </div>
      <table class="table table-bordered">
        <tr>
          <th>店舗の種類</th>
          <td><%= shop.kind%></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= shop.address%></td>
        </tr>
        <tr>
          <th>定休日</th>
          <td><%= shop.holiday%></td>
        </tr>
      </table>
      <div class="d-flex justify-content-end">
        <%= link_to "店舗詳細を見る", shop, class: "btn btn-primary btn-block" %>
      </div>
    </div>
  </div>
</div>

<div class="container d-block d-md-none">
  <div class="d-flex justify-content-between">
    <h2><%= shop.name%></h2>
    <div style="height: 1.5rem">
      <% if current_user == shop.user%>
        <%= link_to "削除する", shop, method: :delete, data: {confirm: "削除してよろしいですか？"}, class: "btn btn-danger btn-sm" %>
      <% end %>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-12" style="height: 250px">
      <% if shop.image.attached? %>
          <%= image_tag shop.image, class: "rounded h-100 w-100"%>
      <% end %>
    </div>
  </div>
  <%= link_to "店舗詳細を見る", shop, class: "btn btn-primary btn-block" %>
</div>

app/views/shops/_shops_list.html.erb
<% shops.each do |shop|%>
<div class="media mb-5">
  <%= render "shops/shop_block", shop: shop %>
</div>
<% end %>
<div class="container">
  <%= paginate shops %>
</div>

app/views/shops/destroy.html.erb
<h1>Shops#destroy</h1>
<p>Find me in app/views/shops/destroy.html.erb</p>

app/views/shops/index.html.erb
<h1>店舗一覧</h1>
<hr/>
<%= render "shops/shops_list", shops: @shops %>

app/views/shops/new.html.erb
<h1>店舗作成</h1>
<div class="row">
    <div class="col-6">
    <%= form_with(model: @shop, local: true) do |f| %>
        <div class="form-group">
            <%= f.label :name, "店舗名" %><br />
            <%= f.text_field :name, autofocus: true, class: "form-control", required: true %>
        </div>
        <div class="form-group">
            <%= f.label :kind, "種類" %><br />
            <%= f.select :kind, {"カフェ": "カフェ", "コンビニ": "コンビニ", "ケーキ屋さん": "ケーキ屋さん"}, {include_blank: "選択してください"}, class: "form-control", required: true  %>
        </div>
        <div class="form-group">
            <%= f.label :address, "住所" %><br />
            <%= f.text_field :address, class: "form-control", required: true  %>
        </div>
        <div class="form-group">
            <%= f.label :holiday, "定休日" %><br />
            <%= f.text_field :holiday, class: "form-control", required: true  %>
        </div>
        <div class="form-group">
            <%= f.label :image, "店舗外観" %><br />
            <%= f.file_field :image, required: true %>
        </div>
        <%= f.submit "店舗作成", class: "btn btn-primary btn-block" %>
    <% end %>
    </div>
</div>

app/views/shops/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <h1><%= @shop.name %>の詳細ページ</h1>
    </div>
    <div class="col-md-3 d-flex h-75 justify-content-end align-self-center mb-3">
      <% if current_user == @shop.user%>
        <%= link_to "この店舗を削除する", @shop, method: :delete, data: {confirm: "削除してよろしいですか？"}, class: "btn btn-danger btn-block h-10px" %>
      <% end %>
    </div>
  </div>
  <hr/>
  <div class="row">
    <div class="col-12 col-md-7">
      <div  style="height: 400px" class="mb-3">
        <% if @shop.image.attached? %>
            <%= image_tag @shop.image, class: "rounded h-100 w-100"%>
        <% end %>
      </div>
      <div class="d-none d-md-flex justify-content-between">
        <%= link_to "店舗一覧に戻る", shops_path, class: "btn btn-primary btn-block"%>
      </div>
    </div>
    <div class="col-md-5 col-12">
      <table class="table table-bordered">
        <tr>
          <th>店舗の種類</th>
          <td><%= @shop.kind%></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @shop.address%></td>
        </tr>
        <tr>
          <th>定休日</th>
          <td><%= @shop.holiday%></td>
        </tr>
      </table>
      <div class="d-flex d-md-none justify-content-between mt-3">
        <%= link_to "店舗一覧に戻る", shops_path, class: "btn btn-primary btn-block"%>
      </div>
    </div>
  </div>
  <br/>
  <div>
    <h2 class="mr-5">レビュー一覧</h2>
    <hr/>
    <div class="container">
      <%= link_to "自分のレビューを投稿する", new_review_path, class: "btn btn-warning btn-block mb-3 mt-3"%>
    </div>
    <%= render "reviews/reviews_list", reviews: @reviews %>
  </div>
</div>