config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show] do
    member do
      get :favorites
      get :myshops
      get :myreviews
    end
  end
  root to: "toppages#index"
  resources :shops, only: [:index, :show, :new, :create, :destroy]
  resources :reviews, only: [:show, :new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :shops
  has_many :reviews
  has_many :favorites
  has_many :favorite_reviews, through: :favorites, source: :review
  
  def favorite(review)
    self.favorites.find_or_create_by(review_id: review.id)
  end
  
  def unfavorite(review)
    favorite = self.favorites.find_by(review_id: review.id)
    favorite.destroy if favorite
  end
  
  def favorite?(review)
    self.favorite_reviews.include?(review)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def favorites
    @user = User.find(params[:id])
    @favorite_reviews = @user.favorite_reviews.page(params[:page]).per(5)
  end
  
  def myshops
    @user = User.find(params[:id])
    @myshops = @user.shops.page(params[:page]).per(5)
  end
  
  def myreviews
    @user = User.find(params[:id])
    @myreviews = @user.reviews.page(params[:page]).per(5)
  end
end

app/views/users/_mypage.html.erb
<div class="row">
  <div class="col-8">
    <h1><%= user.name %>さんのページ</h1>
  </div>
  <div class="col-4 d-flex justify-content-end align-self-center">
    <%= link_to "店舗作成", new_shop_path, class: "btn btn-primary btn-sm mr-1 d-none d-md-block" %>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-danger btn-sm" %>
  </div>
</div>
<hr/>
<div class="row">
    <div class="col-12">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= favorites_user_path(user) %>" class="nav-link <%= 'active' if current_page?(favorites_user_path(user)) %>">食べたいプリン</a></li>
      <li class="nav-item"><a href="<%= myshops_user_path(user) %>" class="nav-link <%= 'active' if current_page?(myshops_user_path(user)) %>">作成した店舗</a></li>
      <li class="nav-item"><a href="<%= myreviews_user_path(user) %>" class="nav-link <%= 'active' if current_page?(myreviews_user_path(user)) %>">作成したレビュー</a></li>
    </ul>
    <% if current_page?(favorites_user_path(user)) %>
        <%= render 'reviews/reviews_list', reviews: lists %>
    <% elsif current_page?(myshops_user_path(user)) %>
        <%= render 'shops/shops_list', shops: lists %>
    <% elsif current_page?(myreviews_user_path(user)) %>
        <%= render 'reviews/reviews_list', reviews: lists %>
    <% end %>
  </div>
</div>

app/views/users/favorites.html.erb
<%= render 'users/mypage', {lists: @favorite_reviews, user: @user} %>

app/views/users/myreviews.html.erb
<%= render 'users/mypage', {lists: @myreviews, user: @user} %>

app/views/users/myshops.html.erb
<%= render 'users/mypage', {lists: @myshops, user: @user} %>

app/views/users/show.html.erb
<h1><%= @user.name %>さんのページ</h1>