config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show] do
    member do
      get :favorites
      get :myshops
      get :myreviews
    end
  end
  root to: "toppages#index"
  resources :shops, only: [:index, :show, :new, :create, :destroy]
  resources :reviews, only: [:show, :new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @reviews = Review.order(id: :desc).page(params[:page]).per(5)
  end
end

app/views/toppages/_topimage.html.erb
<% if current_page?(root_path)%>
  <div id="topPudding">
    <h2 class="d-md-none">プリンな<br/>ひとときを</h2>
    <h1 class="d-none d-md-block">あなたにプリンなひとときを<br>プリン好きによる<br>プリン好きのためのサイト</h1>
  </div>
<% end %>

app/views/toppages/index.html.erb
<div class="row">
  <div class="col-md-9 col-12">
    <h2>New!!</h2>
    <hr/>
    <%= render "reviews/reviews_list", reviews: @reviews %>
  </div>
  <aside class="col-md-3 d-none d-md-block">
    <div class="list-group">
      <%= link_to "マイページ", favorites_user_path(current_user.id), class: "list-group-item list-group-item-action" %>
      <%= link_to "店舗作成", new_shop_path, class: "list-group-item list-group-item-action" %>
      <%= link_to "店舗一覧", shops_path, class: "list-group-item list-group-item-action" %>
    </div>
  </aside>
</div>